name: Add Supabase Secret

on:
  workflow_dispatch:

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install supabase

      - name: Login to Supabase CLI
        run: supabase login ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Add new Supabase Edge Function secret
        run: |
          supabase secrets set \
            MY_NEW_SECRET="${{ secrets.MY_NEW_SECRET }}" \
            --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
