name: Add Supabase Secret

on:
  workflow_dispatch:

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh

      - name: Decrypt .env.preview
        run: dotenvx decrypt --env-file=supabase/functions/.env.preview
        env:
          DOTENV_PRIVATE_KEY_PREVIEW: ${{ secrets.DOTENV_PRIVATE_KEY_PREVIEW }}

      - name: Set Supabase Edge Function secrets from .env.preview
        run: |
          supabase secrets set --env-file supabase/functions/.env.preview --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
