name: Add Supabase Secret

on:
  create:
    branches:
      - '**'  # triggers on creation of any branch


jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Add new Supabase Edge Function secret
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
          MY_NEW_SECRET: ${{ secrets.MY_NEW_SECRET }}
        run: |

          branch_name="${GITHUB_REF#refs/heads/}"

          echo "Detected new branch: $branch_name"

          # Find the branch ID for the given branch name
          branch_id=$(supabase branches list --project-ref "$PROJECT_REF" --experimental | grep "$branch_name" | awk -F '|' '{gsub(/^[ \t]+|[ \t]+$/, "", $1); print $1}')

          # Extract the project_ref from the branch details
          project_ref=$(supabase branches get "$branch_id" --project-ref "$PROJECT_REF" --experimental | awk '/supabase.co/ { split($1, parts, "."); print parts[2] }')

          echo "Using branch_id: $branch_id"
          echo "Using project_ref: $project_ref"

          # Set secrets using the extracted project_ref
          supabase secrets set \
             MY_NEW_SECRET="$MY_NEW_SECRET" \
            --project-ref "$project_ref"